type Mutation {
  createProduct(productInput: [CreateProductInput]): [Product!]!
  removeProduct(id: [ID!]!): [Product]
  updateProduct(productInput: UpdateProductInput): Product!

  createType(typeInput: [CreateTypeInput]): [Type!]!
  removeType(id: [ID!]!): [Type]
  updateType(typeInput: UpdateTypeInput): Type!
}
