type Product {
  id: ID!
  name: String!
  price: String!
  quantity: Int!
  description: String!
  type: Type!
  attributes: [AttributeValue!]!
}
type ProductAttribute {
  id: ID!
  name: String!
  value: String!
}
input CreateProductInput {
  name: String!
  quantity: Int
  price: Float
  description: String
  type: ID!
  attributes: [AttributeValueInput!]!
}
input UpdateProductInput {
  id: ID!
  name: String
  quantity: Int
  price: Float
  description: String
  type: ID
}
